#!/bin/sh
mkdir -p bin && \
scalac -feature -deprecation -d bin -cp ../core/core.jar:../crypto/crypto.jar:../json/json.jar:../time/time.jar src/*.scala && \
jar cmf etc/manifest io.jar -C bin rapture
